name: ubuntu-frame-vnc
base: core20
adopt-info: wayvnc
summary: This is a VNC server for Ubuntu Frame
description: |
  This allows for remote access to a running Ubuntu Frame instance.

grade: devel
confinement: strict

environment:
  LD_LIBRARY_PATH:
    "${SNAP}/usr/local/lib/${SNAPCRAFT_ARCH_TRIPLET}\
     :${SNAP}/graphics/lib\
     :${SNAP_LIBRARY_PATH}\
     :${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}\
     :${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/blas\
     :${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/lapack"
  LIBGL_DRIVERS_PATH: ${SNAP}/graphics/dri
  __EGL_VENDOR_LIBRARY_DIRS: ${SNAP}/graphics/glvnd/egl_vendor.d
  __EGL_EXTERNAL_PLATFORM_CONFIG_DIRS: ${SNAP}/usr/share/egl/egl_external_platform.d
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/libdrm:  # Needed by mesa-core20 on ARM GPUs
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    bind: $SNAP/graphics/drirc.d

apps:
  daemon:
    daemon: simple
    restart-condition: always
    command-chain:
    - bin/run-daemon
    - bin/wayland-launch
    command: usr/local/bin/wayvnc

  ubuntu-frame-vnc:
    command-chain:
    - bin/wayland-launch
    command: usr/local/bin/wayvnc

plugs:
  wayland:
  network-bind:
  graphics-core20:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core20
  opengl:

parts:
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    source-depth: 1
    override-build: |
      ${SNAPCRAFT_PART_BUILD}/build-with-plugs.sh wayland
    stage-packages:
    - inotify-tools

  aml:
    plugin: nil
    source: https://github.com/any1/aml.git
    source-depth: 1

  neatvnc:
    plugin: nil
    source: https://github.com/any1/neatvnc.git
    source-depth: 1
    build-packages:
    - gnutls-dev
    - libdrm-dev
    - libgbm-dev
    - libturbojpeg0-dev
    - zlib1g-dev
    stage-packages:
    - libdrm2
    - libgbm1
    - libgnutls30
    - libturbojpeg
    - zlib1g

  xkbcommon:
    source: https://github.com/xkbcommon/libxkbcommon.git
    source-tag: xkbcommon-1.4.1
    source-depth: 1
    build-packages:
    - bison
    - libxcb-xkb-dev
    - libxml2-dev
    - wayland-protocols
    stage-packages:
    - libxcb-xkb1
    - libxml2
    plugin: meson
    meson-parameters:
    - -Denable-docs=false

  wayvnc:
    after: [aml, neatvnc, xkbcommon]
    source: https://github.com/any1/wayvnc.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$( git describe --tags )"
      mkdir subprojects
      ln -s ../../../aml/src subprojects/aml
      ln -s ../../../neatvnc/src subprojects/neatvnc
    build-packages:
    - libdrm-dev
    - libgbm-dev
    - libpam0g-dev
    - libpixman-1-dev
    - libwayland-dev
    - meson
    - pkg-config
    plugin: meson
    meson-parameters:
    - -Dscreencopy-dmabuf=enabled
    stage-packages:
    - libdrm2
    - libgbm1
    - libpam0g
    - libpixman-1-0
    - libwayland-client0

  cleanup:
    after: [neatvnc, wayvnc]
    plugin: nil
    build-snaps: [ mesa-core20 ]
    override-prime: |
      set -eux
      cd /snap/mesa-core20/current/egl/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$SNAPCRAFT_PRIME/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug doc doc-base drirc.d glvnd libdrm lintian man pkgconfig; do
        rm -rf "$SNAPCRAFT_PRIME/usr/share/$CRUFT"
      done
